### ISSUE TITLE
Failed to build with vite

### ISSUE THREAD

**Issue by Iezuni** [guansss/pixi-live2d-display#97] opened 2023-03-09 06:50 UTC
```
src/live2d/app/Live2DModel.ts:2:31 - error TS2307: Cannot find module 'pixi-live2d-display/extra' or its corresponding type declarations.

2 import { HitAreaFrames } from 'pixi-live2d-display/extra';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```json
  "dependencies": {
    "@types/lodash-es": "^4.17.6",
    "@types/stats.js": "^0.17.0",
    "json5": "^2.2.2",
    "lodash-es": "^4.17.21",
    "pinia": "^2.0.23",
    "pixi-live2d-display": "^0.4.0",
    "pixi.js": "6.5.8",
    "stats.js": "^0.17.0",
    "vue": "^3.2.37"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^3.1.0",
    "typescript": "^4.6.4",
    "vite": "^3.1.0",
    "vue-tsc": "^0.40.4"
  }
```

**Comment by guansss** [comment] 2023-03-12 03:45
Duplicate of #76

**Closed by guansss** 2023-03-12 03:45 UTC
