### ISSUE TITLE
why not found “HitAreaFrames” in "pixi-live2d-display/extra"?

### ISSUE THREAD

**Issue by wuhou123** [guansss/pixi-live2d-display#79] opened 2022-10-13 03:10 UTC
import { HitAreaFrames } from "pixi-live2d-display/extra";
but it`s error,not found, I am very sad...

**Comment by guansss** [comment] 2022-10-14 07:13
Duplicate of #76 

Don't be sad!

**Closed by guansss** 2022-10-14 07:13 UTC
